### ISSUE TITLE
Consider adding a type for `BTreeMap<PublicKey, MDataPermissionSet>`

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#100]
Consider adding a new type for `BTreeMap<PublicKey, MDataPermissionSet>` and replacing it in the six places where it occurs in `mutable_data.rs`, as well as two places in `response.rs`. This will make the code less verbose and will also be useful when we refer to this type in safe_client_libs.

**Comment by clD11** [comment]
In previous commits - `response.rs` has been removed and `mutable_data.rs` has been renamed to `map.rs` and no longer contains type `BTreeMap<PublicKey, MDataPermissionSet>` this can be closed

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
