### ISSUE TITLE
Inconsistent `new` functions for unpub types

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#106]
Unpublished idata as well as mdata (which are always unpublished) always require an owner key to be created, with the `new` function. Unpublished adata, however, do not require an owner key in their `new`. This inconsistency should be addressed when possible.

**Comment by mrcnski** [comment]
Regarding constructors for the different data types, I just remembered about the bottom section of the RFC (easy to miss):

https://github.com/maidsafe/rfcs/blob/master/text/0054-published-and-unpublished-data/0054-published-and-unpublished-data.md#note-about-safe-client-libs-api

Seems to me like this builder pattern can be part of safe-nd itself instead of SCL -- it makes for an elegant alternative to constructors.

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
