### ISSUE TITLE
Export `BLS_PUBLIC_KEY_LEN`

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#118]
Since this constant is being defined separately in both [safe-core](https://github.com/maidsafe/safe_client_libs/blob/b96478fbe1c49f2f0876dcea8e189405426fb503/safe_core/src/ffi/arrays.rs#L18) and soon [safe-cli](https://github.com/maidsafe/safe-cli/pull/260), it makes sense for safe-nd to provide it as a public export.

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
