### ISSUE TITLE
Add missing Get function for AppendOnlyData.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe-nd#119]
`Owners` and `Permissions` can be fetched by their index, but an `Entry` (the data itself) cannot, which would be useful, instead of trying to use `get_in_range`. It seems get by index is just missing here.

Proposing to add

(in `trait AppendOnlyData<P>` in `append_only_data.rs`)

    /// Fetches entry at index.
    fn entry(&self, entry_index: impl Into<Index>) -> Option<&Entry>;

as well as

(in `impl<P> AppendOnlyData<P>` in `append_only_data.rs`)

    /// Returns the entry at the index.
    fn entry(&self, entry_index: impl Into<Index>) -> Option<&Entry> {
        let index = to_absolute_index(entry_index.into(), self.inner.data.len())?;
        self.inner.data.get(index)
    }

and

(in `impl Data` in `append_only_data.rs`)

    /// Fetches entry at index.
    pub fn entry(&self, entry_index: impl Into<Index>) -> Option<&Entry> {
        match self {
            Data::PubSeq(data) => data.entry(entry_index),
            Data::PubUnseq(data) => data.entry(entry_index),
            Data::UnpubSeq(data) => data.entry(entry_index),
            Data::UnpubUnseq(data) => data.entry(entry_index),
        }
    }

as well as corresponding test.

Any other places needing change for this @m-cat ?

**Comment by mrcnski** [comment]
This change sounds good to me 👍 

> Any other places needing change for this @m-cat ?

I think that's all of them

**Comment by S-Coyle** [comment]
Closing - data type replaced with `Sequence` and `Map`
