### ISSUE TITLE
Adjust naming and docs to reflect actual index behaviour

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe-nd#120]
An entry is specified as a struct with key and value.

    pub struct Entry {
        /// Key.
        pub key: Vec<u8>,
        /// Contained data.
        pub value: Vec<u8>,
    }

Then follows this:

    /// Returns the last entries index.
    fn entries_index(&self) -> u64 {
        self.inner.data.len() as u64
     }

The comment and function name are misleading. It is returning the next unused index, not the "last entries index".
Consider a data with 0 items. There is no entry in it, and so it is not returning the last entries index.
A data with 1 item, will return 1, which is not the index of the last entry. The last entry, is the one and only existing Entry, at index 0.

Other examples of this:

    /// If the specified last_entries_index does not match the last recorded entries index, an
    /// error will be returned.
    fn append(&mut self, mut entries: Entries, last_entries_index: u64) -> Result<()> {
    [..]
        if last_entries_index != self.inner.data.len() as u64 {
            return Err(Error::InvalidSuccessor(self.inner.data.len() as u64));
    }

This inconsistency percolates all the way to the top layers of the API.

------------------------

Proposed change is to acknowledge (in all code and names everywhere) that we are actually passing in _next unused index_. Then passing in `0` when expecting an empty AD is exactly as it should be.

Name change in code and documentation:

`last_entries_index` -> `next_unused_index`

**Comment by S-Coyle** [comment]
Closing - data type replaced with `Sequence` and `Map`
