### ISSUE TITLE
Owner/Perm changes uses `next_unused_index` instead of `current_index` as references.

### ISSUE THREAD

**Issue by oetyng** [maidsafe/safe-nd#122]
### Background

In issue #120, it is proposed to correctly identify the index a user passes in when doing a mutation as `next_unused_index` instead of `last_entry_index` (and equivalently for owners and permissions index).

### Problem
This issue describes another, but similar case.
To distinguish when an ownership or permission change happened, we specify the indices of data and one of the other (permissions or owners) at that time. Those indices are of the last item, so what we want is `last_entry_index` (and equivalently for owners and permissions index), and _not_ `next_unused_index`.

It appears that when referring to what data/owner/permission index we were at when doing the change, we are now using `next_unused_index`, i.e. pointing to an index that doesn't yet exist.

#### Example 1:

If we look at `check_unpub_permissiontest` at the bottom of the file `append_only_data.rs`:

```
let mut inner = SeqAppendOnlyData::<UnpubPermissions>::new(XorName([1; 32]), 100);

        // no owner
        let data = Data::from(inner.clone());
        assert_eq!(
            data.check_permission(Action::Read, public_key_0),
            Err(Error::InvalidOwners)
        );

        // no permissions
        unwrap!(inner.append_owner(
            Owner {
                public_key: public_key_0,
                entries_index: 0,
                permissions_index: 0,
            },
            0,
        ));
```

This here seems to me that we're adding an owner before anything else is added.
So, we rightly pass in index 0 for `next_unused_index` for the owner.
But the owner object, states that  entries and permissions is at index 0 when this change happened (the change being that the owner was added). But they are not, those vecs are empty.

#### Example 2:

If we take an arbitrary data version and permissions version, like `2743` and `14` respectively (i.e. those are the last indices of items in those vecs), the way it works now is that when an ownership change happens, it is stored with `data_index: 2743 + 1` and `permissions_index: 14 + 1` - both of which are not yet existing indices.
And when you want to get the actual data, and the actual permissions that were there when the ownership changed, you have to request it with `[owner.data_index - 1]`, instead of just `owner.data_index` and equivalently for permissions. 

### Possible solutions

[...]

**Comment by S-Coyle** [comment]
Closing - I believe the updates to this repo in the last year mean that this issue is no longer valid, unless there are other examples (please correct me if I'm wrong @oetyng )
