### ISSUE TITLE
Description in readme.md

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/safe-nd#124]
The readme for this repository should make it clear why this is needed in addition to the `safe_core` interfaces in the `safe_client_libs` repo. Just so devs know what to expect or not expect this library to do.

More context in this forum thread: https://forum.safedev.org/t/why-only-500-mib-limit-on-upload/2647/6 and from the preceding post:

> This API in safe_core [fn get_unseq_mdata_value] and this API is safe-nd [fn get] might seem similar since they do the same thing i.e. get the value for a particular key in mutable data. The difference is the safe-nd API requires a mutable data object to be available in memory and the safe-core API fetches the value from the network.

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
