### ISSUE TITLE
Module-level documentation not being generated by cargo doc

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#127]
All modules are private so documentation for them does not appear in `cargo doc`.

Options:

1. Move documentation to `lib.rs`
2. Move all documentation to somewhere like a wiki or repo and link to it in the `lib.rs` documentation. This is what we do in `safe_core`.

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
