### ISSUE TITLE
Add job-level if to condition on version change commits

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#155]
Opening an issue from [this commit](https://github.com/maidsafe/safe-nd/pull/149#issuecomment-576437482) so it doesn't get forgotten.

I believe it would be a nice change to reduce some verbosity. IIRC I raised the same PR in a different crate and it also got closed.

**Comment by S-Coyle** [comment]
Closing - this is resolved now with the introduction of the CD pipeline
