### ISSUE TITLE
Questions about the new data types

### ISSUE THREAD

**Issue by happybeing** [maidsafe/safe-nd#257]
Note: this is a copy of a forum [reply](https://safenetforum.org/t/an-overview-of-the-new-data-types/28625/41?u=happybeing) , posted here so it can be addressed at some point.

I was looking at the [docs](https://docs.rs/sn_data_types/0.11.23/sn_data_types/) for sn_data_types to see what might have changed and they seem different to the model presented in the OP. Immutable data is clear enough (PrivateBlob and PublicBlob) but looking at SeqMap and UnseqMap I'm not sure of their correspondence with the OP, or how data that is unpublished becomes published.

I speculate that an UnseqMap is always private (as for Mutable Data in the OP as it is not versioned).

I am though having trouble reconciling the other new types with the descriptions of the types in the OP, so maybe a new overview in a new topic is needed?

For example, the docs day that SeqMap is for unpublished data, unlike the AppendOnly Data of the OP which can be published or unpublished. So there seem to be differences and I can't see how things become published in the API (but maybe this is still to be implemented).

I'm interested because I'm wondering how to implement a publicly writeable data structure to handle submission of issues by non-owners to a decentralised bug tracker (cf. git-bug). I'm looking for something like a public noticeboard or inbox, which can be polled for new issues by any client checking the status of a remote code repository.

One of the questions I was trying to answer is whether I can check the creator of each entry in such a publicly writeable "append only" style data structure? This would help discourage spam, by making it easier for a client to skip over entries created by identities from a blacklist.

**Comment by S-Coyle** [comment]
@happybeing I'm closing this as it's been unactioned for a long time and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
