### ISSUE TITLE
Update encoding

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/safe-nd#44]
We need to make the following changes:

1. Merge the two error variants `FailedToParseCoins` and `FailedToParseIdentity(String)` into a single one `FailedToParse(String)` and ensure a meaningful message is added when constructing one of these variants (e.g. to replace the ones in coins.rs, consider something like `Error::FailedToParse("Can't parse coin units".to_string())` and `Error::FailedToParse("Can't parse coin remainder".to_string())`.
2. Create a utils.rs module.  It should contain:
    * the `verify_signature` method currently in lib.rs
    * a serialisation helper:
    ```rust
    pub(crate) fn serialise<T: Serialize>(data: &T) -> Vec<u8> {
        unwrap!(bincode::serialize(data))
    }
    ```
    * an encoding helper:
    ```rust
    pub(crate) fn encode<T: Serialize>(data: &T) -> String {
        let serialised = serialise(&data);
        multibase::encode(Base::Base32z, &serialised)
    }
    ```
    * a decoding helper:
    ```rust
    pub(crate) fn decode<I: AsRef<str>, O: DeserializeOwned>(encoded: &I) -> Result<O> {
        let (base, decoded) =
            multibase::decode(encoded).map_err(|e| Error::FailedToParse(e.to_string()))?;
        if base != Base::Base32z {
            return Err(Error::FailedToParse(format!(
                "Expected z-base-32 encoding, but got {:?}",
                base
            )));
        }
        Ok(bincode::deserialize(&decoded).map_err(|e| Error::FailedToParse(e.to_string()))?)
    }
    ```
3. Replace all occurrences of `bincode::serialize` with the new helper
4. Remove base64 from the crate and exclusively use multibase z-base-32 encoding
5. Change all existing helpers `encode_to_base64` to `encode_to_z_base_32` and similar change for decode helpers.
6. Provide encode/decode helpers (and tests) for
    * `XorName`
    * `PublicKey`
    * `AppPublicId`
    * `ClientPublicId`
    * `NodePublicId`
    * `PublicId`
    * `ADataAddress`
    * `IDataAddress`
    * `MDataAddress`

**Comment by Yoga07** [comment]
Resolved in #45
