### ISSUE TITLE
Should unsequenced MD kind enum have versioned data?

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe-nd#7]
This, https://github.com/maidsafe/safe-nd/blob/master/src/mutable_data.rs#L19, looks opposite to what is described in RFC.

**Comment by lionel-faber** [comment]
Ah you're right! The Mutable Data struct will be changing completely. This was just an initial struct I put in to get the parts moving in client libs. The proper mutable data struct will come in as defined in maidsafe/safe_client_libs#813

**Comment by nbaksalyar** [comment]
This should be fixed now, cheers :+1:
