### ISSUE TITLE
Remove `Error::description` impl

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#88]
The `description` function has been soft-deprecated:

https://doc.rust-lang.org/1.36.0/std/error/trait.Error.html#method.description

**Comment by Scorch-Dev** [comment]
@m-cat 
Hi, this was posted a almost a year ago now, but I'm wondering if it's still open? There are quite a few of these "help wanted" issues that were opened around this time last year, many of which are still open across various SAFE repos. Although, I'm not sure how valid they are now, a year down the line.

 I was hoping to get my feet wet and start contributing to the project, so dusting off housekeeping items while I explore the codebase seems like a good idea.

**Comment by mrcnski** [comment]
Hi @Scorch-Dev, I'm happy you want to contribute to the project and I'm sure the MaidSafe devs will appreciate it! I've moved on from the company and I'm not familiar with the current state of the codebase. Maybe @lionel1704 can direct you to some issues that could use your eyes. You could also investigate whether this issue is still valid and alert the team if it's not. I'm sure they would appreciate that too!

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
