### ISSUE TITLE
Need custom Serialize impl, if we want to support JSON

### ISSUE THREAD

**Issue by hunterlester** [maidsafe/safe-nd#9]
If we serialize `MutableData` as JSON, a runtime error occurs because a `Vec<u8>` as a key is not valid JSON: https://github.com/maidsafe/safe-nd/blob/master/src/mutable_data.rs#L19

Ref: https://github.com/serde-rs/json/issues/45

**Comment by S-Coyle** [comment]
Closing this as it's old and this repo is being archived - can be recreated in [safe_network](https://github.com/maidsafe/safe_network) if still relevant
