### ISSUE TITLE
Add missing `MData` functions

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#92]
Add functions to `MData` that are implemented by its `Seq` and `Unseq` variants such as `get`, `entries`, `values`, etc. For example, `entries` should match on the variant and return `MDataEntries` instead of `MDataSeqEntries` and `MDataUnseqEntries`. This would simplify some code in SCL and vaults, for example:

```rust
(MDataKind::Seq, Ok(MData::Seq(mdata))) => {
    Response::ListMDataEntries(Ok(mdata.entries().clone().into()))
}
(MDataKind::Unseq, Ok(MData::Unseq(mdata))) => {
    Response::ListMDataEntries(Ok(mdata.entries().clone().into()))
}
```

could become:

```rust
(MDataKind::Seq, Ok(mdata)) if mdata.is_seq() |
(MDataKind::Unseq, Ok(mdata)) if mdata.is_unseq() => {
    Response::ListMDataEntries(Ok(mdata.entries().clone()))
}
```

This is low priority for now but it would make the API nicer to use.

**Comment by S-Coyle** [comment]
Closing - `mdata` no longer used
