### ISSUE TITLE
Panic when trying to fetch an invalid version from a SeqAppendOnly

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-nd#93]
When trying to fetch an invalid version from a `SeqAppendOnly` by invoking `get_adata_range` it crashes, from the stack trace it seem to fail at:

https://github.com/maidsafe/safe-nd/blob/1dc6e6eea9445d21d5864c1b105758f7f566f9bc/src/append_only_data.rs#L476

**Comment by lionel-faber** [comment]
This has already been resolved in #74, specifically in [this commit](https://github.com/maidsafe/safe-nd/commit/5e522f59bbf004a4ce45f9d0fb7d17e33dab4b25). It will be a part of the next update to the stable branch

**Comment by bochaco** [comment]
This has been resolved now as per the test from safe_cli when upgrading to safe-nd v0.2.1
