### ISSUE TITLE
Rework `AppendOperation` struct

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#96]
As this struct is only used in `Request::Append`, it is not necessary for it to contain `address` -- every other adata variant in `Request` already explicitly contains an `address` field. What we can do instead is make `AppendOperation` an enum with `Seq` and `Unseq` variants, so we can collapse the `Request::AppendSeq` and `AppendUnseq` variants into a single `Request::AppendAData` variant. This would simplify the API, but would require changes in safe_vault and safe_client_libs.

**Comment by S-Coyle** [comment]
Closing - struct no longer in use
