### ISSUE TITLE
Fix inconsistencies in `Response` variants

### ISSUE THREAD

**Issue by mrcnski** [maidsafe/safe-nd#99]
Responses that return a single value usually start with `Get`: `GetADataValue`, `GetMDataShell`, etc. Responses that may return multiple values are usually named starting with `List`: `ListMDataValues`, `ListAuthKeysAndVersions`, etc. 

There are two inconsistencies, however, which may cause confusion: `ListMDataUserPermissions`, which returns a single value and should be `GetMDataUserPermissions` to match `GetADataUserPermissions`, and `GetADataPermissions`, which returns a list of values and should be `ListADataPermissions` to match `ListMDataPermissions`.

Fix the above when we do the next refactor.

**Comment by S-Coyle** [comment]
Closing - neither `ListMDataUserPermissions` nor `GetADataPermissions` are now present
